version: 0.2

env:
  secrets-manager:
    LOGIN: cookwithme:LOGIN
    HOST: cookwithme:HOST
    Organization: cookwithme:Organization
    Project: cookwithme:Project

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto11
    commands:
      # Install system dependencies (Amazon Linux uses yum)
      - yum update -y
      - yum install -y jq unzip
      # Set up Python virtual environment
      - python -m venv venv
      - source venv/bin/activate
      # Install Python dependencies
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # Install SonarScanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - chmod +x sonar-scanner-4.8.0.2856-linux/bin/*
      - export PATH=$PATH:$PWD/sonar-scanner-4.8.0.2856-linux/bin

  pre_build:
    commands:
      - python --version
      - java -version
      - sonar-scanner --version

  build:
    commands:
      - echo "Starting SonarCloud analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.sources=. \
          -Dsonar.host.url=$HOST \
          -Dsonar.login=$LOGIN \
          -Dsonar.python.version=3.11
      - echo "Waiting for analysis to complete..."
      - sleep 10
      - echo "Checking Quality Gate status..."
      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi

artifacts:
  files:
    - '**/*'