version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-django pytest-cov mixer
      
  pre_build:
    commands:
      - python manage.py migrate
      
  build:
    commands:
      - pytest --cov=. --cov-report=xml --junitxml=test-results.xml
      
  post_build:
    commands:
      - echo "Test phase completed"

# Removed the reports section